//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimboServiceSoap
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://limbo.com/", ConfigurationName="LimboServiceSoap.RCCServiceSoap")]
    public interface RCCServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://limbo.com/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://limbo.com/GetVersion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> GetVersionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://limbo.com/GetStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<LimboServiceSoap.Status> GetStatusAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://limbo.com/OpenJob", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<LimboServiceSoap.OpenJobResponse> OpenJobAsync(LimboServiceSoap.OpenJobRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://limbo.com/OpenJobEx", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<LimboServiceSoap.LuaValue[]> OpenJobExAsync(LimboServiceSoap.Job job, LimboServiceSoap.ScriptExecution script);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://limbo.com/RenewLease", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<double> RenewLeaseAsync(string jobID, double expirationInSeconds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://limbo.com/Execute", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<LimboServiceSoap.ExecuteResponse> ExecuteAsync(LimboServiceSoap.ExecuteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://limbo.com/ExecuteEx", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<LimboServiceSoap.LuaValue[]> ExecuteExAsync(string jobID, LimboServiceSoap.ScriptExecution script);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://limbo.com/CloseJob", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task CloseJobAsync(string jobID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://limbo.com/BatchJob", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<LimboServiceSoap.BatchJobResponse> BatchJobAsync(LimboServiceSoap.BatchJobRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://limbo.com/BatchJobEx", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<LimboServiceSoap.LuaValue[]> BatchJobExAsync(LimboServiceSoap.Job job, LimboServiceSoap.ScriptExecution script);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://limbo.com/GetExpiration", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<double> GetExpirationAsync(string jobID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://limbo.com/GetAllJobs", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<LimboServiceSoap.GetAllJobsResponse> GetAllJobsAsync(LimboServiceSoap.GetAllJobsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://limbo.com/GetAllJobsEx", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<LimboServiceSoap.Job[]> GetAllJobsExAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://limbo.com/CloseExpiredJobs", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<int> CloseExpiredJobsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://limbo.com/CloseAllJobs", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<int> CloseAllJobsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://limbo.com/Diag", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<LimboServiceSoap.DiagResponse> DiagAsync(LimboServiceSoap.DiagRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://limbo.com/DiagEx", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<LimboServiceSoap.LuaValue[]> DiagExAsync(int type, string jobID);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://limbo.com/")]
    public partial class Status
    {
        
        private string versionField;
        
        private int environmentCountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int environmentCount
        {
            get
            {
                return this.environmentCountField;
            }
            set
            {
                this.environmentCountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://limbo.com/")]
    public partial class LuaValue
    {
        
        private LuaType typeField;
        
        private string valueField;
        
        private LuaValue[] tableField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public LuaType type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public LuaValue[] table
        {
            get
            {
                return this.tableField;
            }
            set
            {
                this.tableField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://limbo.com/")]
    public enum LuaType
    {
        
        /// <remarks/>
        LUA_TNIL,
        
        /// <remarks/>
        LUA_TBOOLEAN,
        
        /// <remarks/>
        LUA_TNUMBER,
        
        /// <remarks/>
        LUA_TSTRING,
        
        /// <remarks/>
        LUA_TTABLE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://limbo.com/")]
    public partial class ScriptExecution
    {
        
        private string nameField;
        
        private string scriptField;
        
        private LuaValue[] argumentsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string script
        {
            get
            {
                return this.scriptField;
            }
            set
            {
                this.scriptField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public LuaValue[] arguments
        {
            get
            {
                return this.argumentsField;
            }
            set
            {
                this.argumentsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://limbo.com/")]
    public partial class Job
    {
        
        private string idField;
        
        private double expirationInSecondsField;
        
        private int categoryField;
        
        private double coresField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public double expirationInSeconds
        {
            get
            {
                return this.expirationInSecondsField;
            }
            set
            {
                this.expirationInSecondsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int category
        {
            get
            {
                return this.categoryField;
            }
            set
            {
                this.categoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public double cores
        {
            get
            {
                return this.coresField;
            }
            set
            {
                this.coresField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OpenJob", WrapperNamespace="http://limbo.com/", IsWrapped=true)]
    public partial class OpenJobRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://limbo.com/", Order=0)]
        public LimboServiceSoap.Job job;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://limbo.com/", Order=1)]
        public LimboServiceSoap.ScriptExecution script;
        
        public OpenJobRequest()
        {
        }
        
        public OpenJobRequest(LimboServiceSoap.Job job, LimboServiceSoap.ScriptExecution script)
        {
            this.job = job;
            this.script = script;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OpenJobResponse", WrapperNamespace="http://limbo.com/", IsWrapped=true)]
    public partial class OpenJobResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://limbo.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("OpenJobResult")]
        public LimboServiceSoap.LuaValue[] OpenJobResult;
        
        public OpenJobResponse()
        {
        }
        
        public OpenJobResponse(LimboServiceSoap.LuaValue[] OpenJobResult)
        {
            this.OpenJobResult = OpenJobResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Execute", WrapperNamespace="http://limbo.com/", IsWrapped=true)]
    public partial class ExecuteRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://limbo.com/", Order=0)]
        public string jobID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://limbo.com/", Order=1)]
        public LimboServiceSoap.ScriptExecution script;
        
        public ExecuteRequest()
        {
        }
        
        public ExecuteRequest(string jobID, LimboServiceSoap.ScriptExecution script)
        {
            this.jobID = jobID;
            this.script = script;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExecuteResponse", WrapperNamespace="http://limbo.com/", IsWrapped=true)]
    public partial class ExecuteResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://limbo.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ExecuteResult", IsNullable=true)]
        public LimboServiceSoap.LuaValue[] ExecuteResult;
        
        public ExecuteResponse()
        {
        }
        
        public ExecuteResponse(LimboServiceSoap.LuaValue[] ExecuteResult)
        {
            this.ExecuteResult = ExecuteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BatchJob", WrapperNamespace="http://limbo.com/", IsWrapped=true)]
    public partial class BatchJobRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://limbo.com/", Order=0)]
        public LimboServiceSoap.Job job;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://limbo.com/", Order=1)]
        public LimboServiceSoap.ScriptExecution script;
        
        public BatchJobRequest()
        {
        }
        
        public BatchJobRequest(LimboServiceSoap.Job job, LimboServiceSoap.ScriptExecution script)
        {
            this.job = job;
            this.script = script;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BatchJobResponse", WrapperNamespace="http://limbo.com/", IsWrapped=true)]
    public partial class BatchJobResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://limbo.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("BatchJobResult", IsNullable=true)]
        public LimboServiceSoap.LuaValue[] BatchJobResult;
        
        public BatchJobResponse()
        {
        }
        
        public BatchJobResponse(LimboServiceSoap.LuaValue[] BatchJobResult)
        {
            this.BatchJobResult = BatchJobResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllJobs", WrapperNamespace="http://limbo.com/", IsWrapped=true)]
    public partial class GetAllJobsRequest
    {
        
        public GetAllJobsRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllJobsResponse", WrapperNamespace="http://limbo.com/", IsWrapped=true)]
    public partial class GetAllJobsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://limbo.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("GetAllJobsResult", IsNullable=true)]
        public LimboServiceSoap.Job[] GetAllJobsResult;
        
        public GetAllJobsResponse()
        {
        }
        
        public GetAllJobsResponse(LimboServiceSoap.Job[] GetAllJobsResult)
        {
            this.GetAllJobsResult = GetAllJobsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Diag", WrapperNamespace="http://limbo.com/", IsWrapped=true)]
    public partial class DiagRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://limbo.com/", Order=0)]
        public int type;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://limbo.com/", Order=1)]
        public string jobID;
        
        public DiagRequest()
        {
        }
        
        public DiagRequest(int type, string jobID)
        {
            this.type = type;
            this.jobID = jobID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DiagResponse", WrapperNamespace="http://limbo.com/", IsWrapped=true)]
    public partial class DiagResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://limbo.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DiagResult", IsNullable=true)]
        public LimboServiceSoap.LuaValue[] DiagResult;
        
        public DiagResponse()
        {
        }
        
        public DiagResponse(LimboServiceSoap.LuaValue[] DiagResult)
        {
            this.DiagResult = DiagResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface RCCServiceSoapChannel : LimboServiceSoap.RCCServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class RCCServiceSoapClient : System.ServiceModel.ClientBase<LimboServiceSoap.RCCServiceSoap>, LimboServiceSoap.RCCServiceSoap
    {
        
        public RCCServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync()
        {
            return base.Channel.HelloWorldAsync();
        }
        
        public System.Threading.Tasks.Task<string> GetVersionAsync()
        {
            return base.Channel.GetVersionAsync();
        }
        
        public System.Threading.Tasks.Task<LimboServiceSoap.Status> GetStatusAsync()
        {
            return base.Channel.GetStatusAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LimboServiceSoap.OpenJobResponse> LimboServiceSoap.RCCServiceSoap.OpenJobAsync(LimboServiceSoap.OpenJobRequest request)
        {
            return base.Channel.OpenJobAsync(request);
        }
        
        public System.Threading.Tasks.Task<LimboServiceSoap.OpenJobResponse> OpenJobAsync(LimboServiceSoap.Job job, LimboServiceSoap.ScriptExecution script)
        {
            LimboServiceSoap.OpenJobRequest inValue = new LimboServiceSoap.OpenJobRequest();
            inValue.job = job;
            inValue.script = script;
            return ((LimboServiceSoap.RCCServiceSoap)(this)).OpenJobAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<LimboServiceSoap.LuaValue[]> OpenJobExAsync(LimboServiceSoap.Job job, LimboServiceSoap.ScriptExecution script)
        {
            return base.Channel.OpenJobExAsync(job, script);
        }
        
        public System.Threading.Tasks.Task<double> RenewLeaseAsync(string jobID, double expirationInSeconds)
        {
            return base.Channel.RenewLeaseAsync(jobID, expirationInSeconds);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LimboServiceSoap.ExecuteResponse> LimboServiceSoap.RCCServiceSoap.ExecuteAsync(LimboServiceSoap.ExecuteRequest request)
        {
            return base.Channel.ExecuteAsync(request);
        }
        
        public System.Threading.Tasks.Task<LimboServiceSoap.ExecuteResponse> ExecuteAsync(string jobID, LimboServiceSoap.ScriptExecution script)
        {
            LimboServiceSoap.ExecuteRequest inValue = new LimboServiceSoap.ExecuteRequest();
            inValue.jobID = jobID;
            inValue.script = script;
            return ((LimboServiceSoap.RCCServiceSoap)(this)).ExecuteAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<LimboServiceSoap.LuaValue[]> ExecuteExAsync(string jobID, LimboServiceSoap.ScriptExecution script)
        {
            return base.Channel.ExecuteExAsync(jobID, script);
        }
        
        public System.Threading.Tasks.Task CloseJobAsync(string jobID)
        {
            return base.Channel.CloseJobAsync(jobID);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LimboServiceSoap.BatchJobResponse> LimboServiceSoap.RCCServiceSoap.BatchJobAsync(LimboServiceSoap.BatchJobRequest request)
        {
            return base.Channel.BatchJobAsync(request);
        }
        
        public System.Threading.Tasks.Task<LimboServiceSoap.BatchJobResponse> BatchJobAsync(LimboServiceSoap.Job job, LimboServiceSoap.ScriptExecution script)
        {
            LimboServiceSoap.BatchJobRequest inValue = new LimboServiceSoap.BatchJobRequest();
            inValue.job = job;
            inValue.script = script;
            return ((LimboServiceSoap.RCCServiceSoap)(this)).BatchJobAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<LimboServiceSoap.LuaValue[]> BatchJobExAsync(LimboServiceSoap.Job job, LimboServiceSoap.ScriptExecution script)
        {
            return base.Channel.BatchJobExAsync(job, script);
        }
        
        public System.Threading.Tasks.Task<double> GetExpirationAsync(string jobID)
        {
            return base.Channel.GetExpirationAsync(jobID);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LimboServiceSoap.GetAllJobsResponse> LimboServiceSoap.RCCServiceSoap.GetAllJobsAsync(LimboServiceSoap.GetAllJobsRequest request)
        {
            return base.Channel.GetAllJobsAsync(request);
        }
        
        public System.Threading.Tasks.Task<LimboServiceSoap.GetAllJobsResponse> GetAllJobsAsync()
        {
            LimboServiceSoap.GetAllJobsRequest inValue = new LimboServiceSoap.GetAllJobsRequest();
            return ((LimboServiceSoap.RCCServiceSoap)(this)).GetAllJobsAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<LimboServiceSoap.Job[]> GetAllJobsExAsync()
        {
            return base.Channel.GetAllJobsExAsync();
        }
        
        public System.Threading.Tasks.Task<int> CloseExpiredJobsAsync()
        {
            return base.Channel.CloseExpiredJobsAsync();
        }
        
        public System.Threading.Tasks.Task<int> CloseAllJobsAsync()
        {
            return base.Channel.CloseAllJobsAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LimboServiceSoap.DiagResponse> LimboServiceSoap.RCCServiceSoap.DiagAsync(LimboServiceSoap.DiagRequest request)
        {
            return base.Channel.DiagAsync(request);
        }
        
        public System.Threading.Tasks.Task<LimboServiceSoap.DiagResponse> DiagAsync(int type, string jobID)
        {
            LimboServiceSoap.DiagRequest inValue = new LimboServiceSoap.DiagRequest();
            inValue.type = type;
            inValue.jobID = jobID;
            return ((LimboServiceSoap.RCCServiceSoap)(this)).DiagAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<LimboServiceSoap.LuaValue[]> DiagExAsync(int type, string jobID)
        {
            return base.Channel.DiagExAsync(type, jobID);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
    }
}
